--------------------------------------------------------
--  파일이 생성됨 - 목요일-11월-01-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."ADMIN" 
   (	"A_IDX" NUMBER(10,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"AGE" NUMBER(10,0), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDR" VARCHAR2(30 BYTE), 
	"RANK" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BASK_COMMENT
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."BASK_COMMENT" 
   (	"C_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"BASK_IDX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HB_BASKETBALL
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."HB_BASKETBALL" 
   (	"BASK_IDX" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(30 BYTE), 
	"H_IDX" NUMBER, 
	"L_IDX" NUMBER, 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"REQ_MEMBER" NUMBER, 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"HIT" NUMBER DEFAULT 0, 
	"GOOD" NUMBER, 
	"BAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOBBY
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."HOBBY" 
   (	"H_IDX" NUMBER, 
	"H_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HREQ_COMMENT
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."HREQ_COMMENT" 
   (	"C_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"HR_IDX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_REQUEST
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."H_REQUEST" 
   (	"HR_IDX" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JAVA_COMMENT
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."JAVA_COMMENT" 
   (	"C_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"JAVA_IDX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."LOCATION" 
   (	"L_IDX" NUMBER, 
	"L_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."MEMBER" 
   (	"U_IDX" NUMBER(10,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"AGE" NUMBER(10,0), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDR" VARCHAR2(30 BYTE), 
	"RANK" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"POINT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SB_JAVA
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."SB_JAVA" 
   (	"JAVA_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"S_IDX" NUMBER(10,0), 
	"L_IDX" NUMBER(10,0), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"REQ_MEMBER" NUMBER(10,0), 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"HIT" NUMBER DEFAULT 0, 
	"GOOD" NUMBER, 
	"BAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SREQ_COMMENT
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."SREQ_COMMENT" 
   (	"C_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"SR_IDX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDY
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."STUDY" 
   (	"S_IDX" NUMBER(10,0), 
	"S_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table S_REQUEST
--------------------------------------------------------

  CREATE TABLE "SOCIALHS"."S_REQUEST" 
   (	"HS_IDX" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOCIALHS.ADMIN
SET DEFINE OFF;
REM INSERTING into SOCIALHS.BASK_COMMENT
SET DEFINE OFF;
REM INSERTING into SOCIALHS.HB_BASKETBALL
SET DEFINE OFF;
REM INSERTING into SOCIALHS.HOBBY
SET DEFINE OFF;
REM INSERTING into SOCIALHS.HREQ_COMMENT
SET DEFINE OFF;
REM INSERTING into SOCIALHS.H_REQUEST
SET DEFINE OFF;
REM INSERTING into SOCIALHS.JAVA_COMMENT
SET DEFINE OFF;
REM INSERTING into SOCIALHS.LOCATION
SET DEFINE OFF;
REM INSERTING into SOCIALHS.MEMBER
SET DEFINE OFF;
REM INSERTING into SOCIALHS.SB_JAVA
SET DEFINE OFF;
REM INSERTING into SOCIALHS.SREQ_COMMENT
SET DEFINE OFF;
REM INSERTING into SOCIALHS.STUDY
SET DEFINE OFF;
REM INSERTING into SOCIALHS.S_REQUEST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HB_BASKETBALL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIALHS"."HB_BASKETBALL_PK" ON "SOCIALHS"."HB_BASKETBALL" ("BASK_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007413
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIALHS"."SYS_C007413" ON "SOCIALHS"."MEMBER" ("U_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index H_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIALHS"."H_REQUEST_PK" ON "SOCIALHS"."H_REQUEST" ("HR_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIALHS"."LOCATION_PK" ON "SOCIALHS"."LOCATION" ("L_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HOBBY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIALHS"."HOBBY_PK" ON "SOCIALHS"."HOBBY" ("H_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDY
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."STUDY" ADD PRIMARY KEY ("S_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."STUDY" MODIFY ("S_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("L_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."LOCATION" MODIFY ("L_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."LOCATION" MODIFY ("L_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOBBY
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."HOBBY" ADD CONSTRAINT "HOBBY_PK" PRIMARY KEY ("H_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."HOBBY" MODIFY ("H_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SREQ_COMMENT
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."SREQ_COMMENT" ADD PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."SREQ_COMMENT" MODIFY ("SR_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SREQ_COMMENT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SREQ_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SREQ_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."MEMBER" ADD CONSTRAINT "SYS_C007413" PRIMARY KEY ("U_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table H_REQUEST
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."H_REQUEST" ADD CONSTRAINT "H_REQUEST_PK" PRIMARY KEY ("HR_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."H_REQUEST" MODIFY ("HR_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HB_BASKETBALL
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("BAD" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("GOOD" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" ADD CONSTRAINT "HB_BASKETBALL_PK" PRIMARY KEY ("BASK_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("L_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("H_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HB_BASKETBALL" MODIFY ("BASK_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JAVA_COMMENT
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."JAVA_COMMENT" ADD PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."JAVA_COMMENT" MODIFY ("JAVA_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."JAVA_COMMENT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."JAVA_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."JAVA_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BASK_COMMENT
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."BASK_COMMENT" ADD PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."BASK_COMMENT" MODIFY ("BASK_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."BASK_COMMENT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."BASK_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."BASK_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table S_REQUEST
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."S_REQUEST" ADD PRIMARY KEY ("HS_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."S_REQUEST" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."S_REQUEST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."S_REQUEST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."S_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."ADMIN" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."ADMIN" ADD PRIMARY KEY ("A_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."ADMIN" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HREQ_COMMENT
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."HREQ_COMMENT" ADD PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."HREQ_COMMENT" MODIFY ("HR_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HREQ_COMMENT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HREQ_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."HREQ_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SB_JAVA
--------------------------------------------------------

  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("BAD" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("GOOD" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" ADD PRIMARY KEY ("JAVA_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("L_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("S_IDX" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOCIALHS"."SB_JAVA" MODIFY ("ID" NOT NULL ENABLE);
